# SellGUI Configuration

gui:
  # The title of the /sell GUI. Color codes are supported.
  title: "&2&lVerkaufsmenü"

  # The message displayed to the player after selling items.
  # Use %price% as a placeholder for the total sale price.
  # This message appears above the hotbar.
  sell-message: "&a+&f%price% €"

  # The format for numbers, using Java's DecimalFormat.
  # Examples: #,##0.00 (1,234.56) or 0.00 (1234.56)
  number-format: "#,##0.00"

  # When enabled, this will send a message to a player if they try to sell an item that isn't in prices.yml
  debug-unpriced-items: true

  # Configuration for the item that shows the total price.
  total-worth-item:
    material: "GOLD_NUGGET"
    name: "&6&lGesamtwert"
    lore:
      - "&7Der Gesamtwert aller Items"
      - "&7in diesem Menü beträgt:"
      - "&e%total% €"
      - ""
      - "&cDu kannst diesen Gegenstand nicht nehmen."

filler-item:
  enabled: true
  material: "GRAY_STAINED_GLASS_PANE"
  name: " "
