# SellGUI Configuration

gui:
  # The title of the /sell GUI. Color codes are supported.
  title: "&2&lVerkaufsmenü"

  # The message displayed to the player after selling items.
  # Use %price% as a placeholder for the total sale price.
  # This message appears above the hotbar.
  sell-message: "&a+&f%price% €"

  # Configuration for the item that shows the total price.
  total-worth-item:
    material: "GOLD_NUGGET"
    name: "&6&lGesamtwert"
    lore:
      - "&7Der Gesamtwert aller Items"
      - "&7in diesem Menü beträgt:"
      - "&e%total% €"
      - ""
      - "&cDu kannst diesen Gegenstand nicht nehmen."

filler-item:
  enabled: true
  material: "GRAY_STAINED_GLASS_PANE"
  name: " "
